"""Compact DTOs for FastAPI. Must not load joblib or open Kite."""

from __future__ import annotations

from typing import Any, Protocol


class UiReadModel(Protocol):
    def overview(self) -> dict[str, Any]: ...
    def maturity(self) -> dict[str, Any]: ...
    def signals(self, *, limit: int = 200) -> dict[str, Any]: ...
    def account(self, *, fill_limit: int = 100) -> dict[str, Any]: ...
    def decisions(self, *, limit: int = 100) -> dict[str, Any]: ...
    def health(self) -> dict[str, Any]: ...
    def quote(self, symbol: str) -> dict[str, Any]: ...
